### ISSUE TITLE
Is not work for CreateApplicationBuilder

### ISSUE THREAD

**Issue by AndresGMD** [gao-artur/WorkerService.Testing#1]
Hi.

Currently I'm using var builder = Host.CreateApplicationBuilder(args); in my initial configuration to work with Workerservice

This is my Appfactory for testing

```c#
public class WorkerAppFactory : WorkerApplicationFactory<Program>
{
    private IHost host;
    protected override void ConfigureHost(IHostBuilder builder)
    {
        var configuration = TestFixtures.GetContigurationTest(TestFixtures.Settings!);

        builder.UseEnvironment("Local");
        builder.ConfigureAppConfiguration((context, config) =>
            {
                // Add test configuration
                config.AddConfiguration(configuration);
            });
        builder.ConfigureServices(services =>
        {
            services.AddTestMongoDb();
        });
    }
```

Bu when I exceuted using StarAsync I get the following Error:

> System.AggregateException : One or more errors occurred. (Method 'CreateHostBuilder' was not found in class 'Program' (Assembly: TripArc.Excursion.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null))
> ---- System.Exception : Method 'CreateHostBuilder' was not found in class 'Program' (Assembly: TripArc.Excursion.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at TripArc.Excursion.Api.Unit.Tests.BackgroundServiceTest.UpdateMetatronDescriptionWorkerTest..ctor(WorkerAppFactory workerFactory) in C:\Users\AndrésGustavoMUÑOZ\Projects\Trip-Arc\DMX\TripArc.Excursions.Api\TripArc.Excursion.Api.Unit.Tests\BackgroundServiceTest\UpdateMetatronDescriptionWorkerTest.cs:line 34
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
> ----- Inner Stack Trace -----
>    at WorkerService.Testing.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
>    at WorkerService.Testing.HostFactoryResolver.ResolveHostBuilderFactory(Assembly assembly)
>    at WorkerService.Testing.WorkerApplicationFactory`1.CreateHostBuilder()

   
   How can I use with 

var builder = Host.CreateApplicationBuilder(args); ?

**Comment by gao-artur** [comment]
The `WorkerApplicationFactory`, similar to the older `WebApplicationFactory,` expects your entry point class to have a `CreateHostBuilder` method by convention. So, your `Program.cs` should look similar to this:
```c#
public static class Program
{
    public static void Main(string[] args)
    {
        reateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureServices(services =>
            {
                services.AddHostedService<Worker>();
            });
}
```

If you are using the newer VS templates, it probably looks like this
```C#
public class Program
{
    public static void Main(string[] args)
    {
        IHost host = Host.CreateDefaultBuilder(args)
            .ConfigureServices(services =>
            {
                services.AddHostedService<Worker>();
            })
            .Build();

        host.Run();
    }
}
```

Sorry, I haven't updated this code since .NET Core 3, so it won't work with newer templates. Maybe try this [solution](https://stackoverflow.com/questions/77211786/how-to-start-a-full-net-core-worker-service-in-an-integration-end-to-end-test/77737308#77737308) instead (I didn't try it)
